[package]
name = "nu_plugin_ldap"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
keyring = "2.3.2"
ldap3 = "0.11.3"
nu-plugin = "0.91.0"
nu-protocol = "0.91.0"
whoami = "1.5.0"
